import { makeStyles, tokens } from '@fluentui/react-components'
import { NARROW_VIEWPORT_QUERY, mobileTouchTarget, mobileTouchTargetHeight } from '../../styles/touchTargets'

export const useMessageListStyles = makeStyles({
  root: {
    flex: 1,
    minWidth: 0,
    overflowY: 'auto',
    padding: tokens.spacingVerticalXXL,
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalL,
  },
  message: {
    display: 'flex',
    gap: tokens.spacingHorizontalM,
    minWidth: 0,
    maxWidth: 'min(800px, 100%)',
    alignSelf: 'flex-start',
  },
  userMessage: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
  },
  messageContent: {
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: tokens.spacingVerticalM,
    borderRadius: tokens.borderRadiusLarge,
    flex: 1,
    minWidth: 0,
    maxWidth: '100%',
  },
  userMessageContent: {
    backgroundColor: tokens.colorBrandBackground2,
    border: `1px solid ${tokens.colorBrandStroke2}`,
  },
  messageText: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  collapsedPrompt: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacingVerticalM,
    minWidth: 0,
  },
  promptActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
    '& button': {
      ...mobileTouchTarget,
    },
  },
  promptDetails: {
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    '& summary': {
      display: 'flex',
      alignItems: 'center',
      minHeight: '44px',
      width: 'fit-content',
      color: tokens.colorBrandForegroundLink,
      cursor: 'pointer',
      fontWeight: tokens.fontWeightSemibold,
      ':focus-visible': {
        outline: `2px solid ${tokens.colorStrokeFocus2}`,
        outlineOffset: '2px',
      },
    },
  },
  fullPrompt: {
    maxHeight: '480px',
    overflow: 'auto',
    padding: tokens.spacingHorizontalM,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
  },
  fullPromptText: {
    margin: 0,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
  },
  messageJsonBlock: {
    margin: 0,
    padding: tokens.spacingHorizontalS,
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    overflowX: 'auto',
    maxHeight: '400px',
    overflowY: 'auto',
  },
  messageFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: tokens.spacingVerticalXS,
    gap: '15px',
  },
  timestamp: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
  },
  role: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    fontStyle: 'italic',
  },
  footerDetails: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
  },
  pieceRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    rowGap: tokens.spacingVerticalXS,
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
  },
  displayPiecesContainer: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: tokens.spacingVerticalS,
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
  },
  scoreList: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalXXS,
    flexShrink: 0,
    alignSelf: 'flex-end',
  },
  scoreChip: {
    minWidth: '32px',
    maxWidth: 'min(160px, calc(100vw - 64px))',
    height: '32px',
    padding: `0 ${tokens.spacingHorizontalXS}`,
    overflow: 'hidden',
    ...mobileTouchTarget,
  },
  scoreChipValue: {
    display: 'block',
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  stackedScoreButton: {
    minWidth: '48px',
    maxWidth: 'min(160px, calc(100vw - 64px))',
    height: '40px',
    padding: `0 ${tokens.spacingHorizontalXS}`,
    overflow: 'visible',
    ...mobileTouchTarget,
  },
  scoreStack: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'flex-start',
    minWidth: 0,
    maxWidth: '100%',
  },
  scoreStackOvalBack: {
    position: 'absolute',
    inset: 0,
    transform: `translate(${tokens.spacingHorizontalXS}, ${tokens.spacingVerticalXS})`,
    borderRadius: '999px',
    border: `1px solid ${tokens.colorBrandStroke2}`,
    backgroundColor: tokens.colorBrandBackground2,
    zIndex: 0,
  },
  scoreStackOvalMiddle: {
    position: 'absolute',
    inset: 0,
    transform: `translate(${tokens.spacingHorizontalXXS}, ${tokens.spacingVerticalXXS})`,
    borderRadius: '999px',
    border: `1px solid ${tokens.colorBrandStroke2}`,
    backgroundColor: tokens.colorBrandBackground2,
    zIndex: 1,
  },
  scoreStackOvalFront: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '30px',
    minHeight: '20px',
    padding: `0 ${tokens.spacingHorizontalXS}`,
    borderRadius: '999px',
    border: `1px solid ${tokens.colorBrandStroke2}`,
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase200,
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    zIndex: 2,
  },
  multiScorePopover: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: tokens.spacingVerticalM,
    minWidth: 0,
    width: 'min(560px, calc(100vw - 32px))',
    maxWidth: 'calc(100vw - 32px)',
  },
  scoreTabBar: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: tokens.spacingHorizontalXS,
    minWidth: 0,
  },
  scoreTabs: {
    flex: '1 1 0',
    width: 0,
    minWidth: 0,
    maxWidth: '100%',
    columnGap: tokens.spacingHorizontalXS,
    overflowX: 'hidden',
    overflowY: 'hidden',
  },
  scoreTab: {
    flex: '0 0 72px',
    width: '72px',
    minWidth: '72px',
    padding: `0 ${tokens.spacingHorizontalM}`,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    ...mobileTouchTargetHeight,
  },
  scoreOverflowButton: {
    position: 'relative',
    zIndex: 1,
    width: '112px',
    minWidth: '112px',
    flexShrink: 0,
    ...mobileTouchTarget,
  },
  scoreMenuItem: {
    ...mobileTouchTargetHeight,
  },
  scoreTabValue: {
    display: 'block',
    minWidth: 0,
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  scoreSurface: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: tokens.spacingVerticalXS,
    width: 'min(360px, calc(100vw - 64px))',
    minWidth: 0,
    maxWidth: '100%',
  },
  scoreRow: {
    display: 'flex',
    alignItems: 'flex-start',
    columnGap: tokens.spacingHorizontalS,
    width: '100%',
    minWidth: 0,
  },
  scoreLabel: {
    flex: '0 0 72px',
    color: tokens.colorNeutralForeground2,
  },
  scoreValue: {
    display: 'block',
    flex: '0 1 auto',
    minWidth: 0,
    maxWidth: '100%',
    height: 'auto',
    whiteSpace: 'normal',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  scoreRationale: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: tokens.spacingVerticalXXS,
    marginTop: tokens.spacingVerticalXS,
    paddingTop: tokens.spacingVerticalXS,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  scoreRationaleText: {
    color: tokens.colorNeutralForeground2,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    maxHeight: '30vh',
    overflowY: 'auto',
  },
  loadingEllipsis: {
    fontSize: tokens.fontSizeBase500,
    animationName: {
      '0%': { opacity: '0.3' },
      '50%': { opacity: '1' },
      '100%': { opacity: '0.3' },
    },
    animationDuration: '1.5s',
    animationIterationCount: 'infinite',
  },
  attachmentsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacingHorizontalS,
    marginTop: tokens.spacingVerticalS,
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
  },
  attachmentItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    rowGap: tokens.spacingVerticalXS,
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
  },
  imageContainer: {
    position: 'relative' as const,
    display: 'inline-block',
    width: 'fit-content',
    maxWidth: 'min(400px, 100%)',
    maxHeight: '400px',
    minWidth: 'min(100px, 100%)',
    minHeight: '60px',
  },
  imageSpinner: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  attachmentPreview: {
    display: 'block',
    width: 'auto',
    height: 'auto',
    maxWidth: '100%',
    maxHeight: '400px',
    borderRadius: tokens.borderRadiusMedium,
    objectFit: 'contain',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  attachmentPreviewHidden: {
    maxWidth: '100%',
    maxHeight: '400px',
    borderRadius: tokens.borderRadiusMedium,
    objectFit: 'contain',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    visibility: 'hidden' as const,
    width: 0,
    height: 0,
  },
  videoPreview: {
    display: 'block',
    width: 'auto',
    height: 'auto',
    maxWidth: 'min(400px, 100%)',
    maxHeight: '300px',
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  audioPreview: {
    width: '300px',
    maxWidth: '100%',
  },
  attachmentFile: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    padding: tokens.spacingVerticalS,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    minWidth: 0,
    maxWidth: '100%',
  },
  attachmentFileName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  attachmentOpenLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold as unknown as string,
    textDecoration: 'none',
    flexShrink: 0,
    ...mobileTouchTarget,
    ':hover': {
      backgroundColor: tokens.colorBrandBackgroundHover,
      color: tokens.colorNeutralForegroundOnBrand,
    },
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: tokens.spacingVerticalM,
  },
  errorContainer: {
    marginTop: tokens.spacingVerticalS,
  },
  mediaActions: {
    display: 'flex',
    gap: tokens.spacingHorizontalXXS,
    marginTop: tokens.spacingVerticalXXS,
  },
  messageActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: tokens.spacingHorizontalXXS,
    marginTop: tokens.spacingVerticalS,
    [NARROW_VIEWPORT_QUERY]: {
      flexWrap: 'wrap',
    },
  },
  messageActionButton: {
    minWidth: 'auto',
    padding: '2px',
    ...mobileTouchTarget,
  },
  reasoningContainer: {
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    marginBottom: tokens.spacingVerticalS,
  },
  reasoningLabel: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: tokens.spacingVerticalXXS,
  },
  reasoningText: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    lineHeight: tokens.lineHeightBase200,
  },
  originalSection: {
    marginBottom: tokens.spacingVerticalS,
    opacity: 0.6,
  },
  originalText: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    color: tokens.colorNeutralForeground3,
  },
  sectionLabel: {
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: tokens.spacingVerticalXXS,
    cursor: 'default',
  },
  sectionDivider: {
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    marginTop: tokens.spacingVerticalS,
    marginBottom: tokens.spacingVerticalS,
  },
  convertedLabel: {
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorBrandForeground1,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: tokens.spacingVerticalXXS,
    cursor: 'default',
  },
})
